package com.xeniac.warrantyrostermanager.mainactivity.warrantydetailsfragment;// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL plugin from the GraphQL queries it found.
// It should not be modified by hand.
//

import com.apollographql.apollo.api.Mutation;
import com.apollographql.apollo.api.Operation;
import com.apollographql.apollo.api.OperationName;
import com.apollographql.apollo.api.Response;
import com.apollographql.apollo.api.ResponseField;
import com.apollographql.apollo.api.ScalarTypeAdapters;
import com.apollographql.apollo.api.internal.InputFieldMarshaller;
import com.apollographql.apollo.api.internal.InputFieldWriter;
import com.apollographql.apollo.api.internal.OperationRequestBodyComposer;
import com.apollographql.apollo.api.internal.QueryDocumentMinifier;
import com.apollographql.apollo.api.internal.ResponseFieldMapper;
import com.apollographql.apollo.api.internal.ResponseFieldMarshaller;
import com.apollographql.apollo.api.internal.ResponseReader;
import com.apollographql.apollo.api.internal.ResponseWriter;
import com.apollographql.apollo.api.internal.SimpleOperationResponseParser;
import com.apollographql.apollo.api.internal.UnmodifiableMapBuilder;
import com.apollographql.apollo.api.internal.Utils;
import com.xeniac.warrantyrostermanager.CustomType;

import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;

import okio.Buffer;
import okio.BufferedSource;
import okio.ByteString;

import org.jetbrains.annotations.NotNull;

public final class DeleteWarrantyMutation implements Mutation<DeleteWarrantyMutation.Data, DeleteWarrantyMutation.Data, DeleteWarrantyMutation.Variables> {
    public static final String OPERATION_ID = "2a0a32c6e346da2830b68bdf67cb60cf57c3f9bc29100e119bad7f1665bba652";

    public static final String QUERY_DOCUMENT = QueryDocumentMinifier.minify(
            "mutation deleteWarranty($id: ID!) {\n"
                    + "  deleteWarranty(id: $id)\n"
                    + "}"
    );

    public static final OperationName OPERATION_NAME = new OperationName() {
        @Override
        public String name() {
            return "deleteWarranty";
        }
    };

    private final DeleteWarrantyMutation.Variables variables;

    public DeleteWarrantyMutation(@NotNull String id) {
        Utils.checkNotNull(id, "id == null");
        variables = new DeleteWarrantyMutation.Variables(id);
    }

    @Override
    public String operationId() {
        return OPERATION_ID;
    }

    @Override
    public String queryDocument() {
        return QUERY_DOCUMENT;
    }

    @Override
    public DeleteWarrantyMutation.Data wrapData(DeleteWarrantyMutation.Data data) {
        return data;
    }

    @Override
    public DeleteWarrantyMutation.Variables variables() {
        return variables;
    }

    @Override
    public ResponseFieldMapper<DeleteWarrantyMutation.Data> responseFieldMapper() {
        return new Data.Mapper();
    }

    public static Builder builder() {
        return new Builder();
    }

    @Override
    public OperationName name() {
        return OPERATION_NAME;
    }

    @Override
    @NotNull
    public Response<DeleteWarrantyMutation.Data> parse(@NotNull final BufferedSource source,
                                                       @NotNull final ScalarTypeAdapters scalarTypeAdapters) throws IOException {
        return SimpleOperationResponseParser.parse(source, this, scalarTypeAdapters);
    }

    @Override
    @NotNull
    public Response<DeleteWarrantyMutation.Data> parse(@NotNull final ByteString byteString,
                                                       @NotNull final ScalarTypeAdapters scalarTypeAdapters) throws IOException {
        return parse(new Buffer().write(byteString), scalarTypeAdapters);
    }

    @Override
    @NotNull
    public Response<DeleteWarrantyMutation.Data> parse(@NotNull final BufferedSource source) throws
            IOException {
        return parse(source, ScalarTypeAdapters.DEFAULT);
    }

    @Override
    @NotNull
    public Response<DeleteWarrantyMutation.Data> parse(@NotNull final ByteString byteString) throws
            IOException {
        return parse(byteString, ScalarTypeAdapters.DEFAULT);
    }

    @Override
    @NotNull
    public ByteString composeRequestBody(@NotNull final ScalarTypeAdapters scalarTypeAdapters) {
        return OperationRequestBodyComposer.compose(this, false, true, scalarTypeAdapters);
    }

    @NotNull
    @Override
    public ByteString composeRequestBody() {
        return OperationRequestBodyComposer.compose(this, false, true, ScalarTypeAdapters.DEFAULT);
    }

    @Override
    @NotNull
    public ByteString composeRequestBody(final boolean autoPersistQueries,
                                         final boolean withQueryDocument, @NotNull final ScalarTypeAdapters scalarTypeAdapters) {
        return OperationRequestBodyComposer.compose(this, autoPersistQueries, withQueryDocument, scalarTypeAdapters);
    }

    public static final class Builder {
        private @NotNull
        String id;

        Builder() {
        }

        public Builder id(@NotNull String id) {
            this.id = id;
            return this;
        }

        public DeleteWarrantyMutation build() {
            Utils.checkNotNull(id, "id == null");
            return new DeleteWarrantyMutation(id);
        }
    }

    public static final class Variables extends Operation.Variables {
        private final @NotNull
        String id;

        private final transient Map<String, Object> valueMap = new LinkedHashMap<>();

        Variables(@NotNull String id) {
            this.id = id;
            this.valueMap.put("id", id);
        }

        public @NotNull
        String id() {
            return id;
        }

        @Override
        public Map<String, Object> valueMap() {
            return Collections.unmodifiableMap(valueMap);
        }

        @Override
        public InputFieldMarshaller marshaller() {
            return new InputFieldMarshaller() {
                @Override
                public void marshal(InputFieldWriter writer) throws IOException {
                    writer.writeCustom("id", CustomType.ID, id);
                }
            };
        }
    }

    /**
     * Data from the response after executing this GraphQL operation
     */
    public static class Data implements Operation.Data {
        static final ResponseField[] $responseFields = {
                ResponseField.forString("deleteWarranty", "deleteWarranty", new UnmodifiableMapBuilder<String, Object>(1)
                        .put("id", new UnmodifiableMapBuilder<String, Object>(2)
                                .put("kind", "Variable")
                                .put("variableName", "id")
                                .build())
                        .build(), false, Collections.<ResponseField.Condition>emptyList())
        };

        final @NotNull
        String deleteWarranty;

        private transient volatile String $toString;

        private transient volatile int $hashCode;

        private transient volatile boolean $hashCodeMemoized;

        public Data(@NotNull String deleteWarranty) {
            this.deleteWarranty = Utils.checkNotNull(deleteWarranty, "deleteWarranty == null");
        }

        public @NotNull
        String deleteWarranty() {
            return this.deleteWarranty;
        }

        @SuppressWarnings({"rawtypes", "unchecked"})
        public ResponseFieldMarshaller marshaller() {
            return new ResponseFieldMarshaller() {
                @Override
                public void marshal(ResponseWriter writer) {
                    writer.writeString($responseFields[0], deleteWarranty);
                }
            };
        }

        @Override
        public String toString() {
            if ($toString == null) {
                $toString = "Data{"
                        + "deleteWarranty=" + deleteWarranty
                        + "}";
            }
            return $toString;
        }

        @Override
        public boolean equals(Object o) {
            if (o == this) {
                return true;
            }
            if (o instanceof Data) {
                Data that = (Data) o;
                return this.deleteWarranty.equals(that.deleteWarranty);
            }
            return false;
        }

        @Override
        public int hashCode() {
            if (!$hashCodeMemoized) {
                int h = 1;
                h *= 1000003;
                h ^= deleteWarranty.hashCode();
                $hashCode = h;
                $hashCodeMemoized = true;
            }
            return $hashCode;
        }

        public static final class Mapper implements ResponseFieldMapper<Data> {
            @Override
            public Data map(ResponseReader reader) {
                final String deleteWarranty = reader.readString($responseFields[0]);
                return new Data(deleteWarranty);
            }
        }
    }
}