package com.xeniac.warrantyroster.mainactivity.changepasswordfragment;// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL plugin from the GraphQL queries it found.
// It should not be modified by hand.
//

import com.apollographql.apollo.api.Mutation;
import com.apollographql.apollo.api.Operation;
import com.apollographql.apollo.api.OperationName;
import com.apollographql.apollo.api.Response;
import com.apollographql.apollo.api.ResponseField;
import com.apollographql.apollo.api.ScalarTypeAdapters;
import com.apollographql.apollo.api.internal.InputFieldMarshaller;
import com.apollographql.apollo.api.internal.InputFieldWriter;
import com.apollographql.apollo.api.internal.OperationRequestBodyComposer;
import com.apollographql.apollo.api.internal.QueryDocumentMinifier;
import com.apollographql.apollo.api.internal.ResponseFieldMapper;
import com.apollographql.apollo.api.internal.ResponseFieldMarshaller;
import com.apollographql.apollo.api.internal.ResponseReader;
import com.apollographql.apollo.api.internal.ResponseWriter;
import com.apollographql.apollo.api.internal.SimpleOperationResponseParser;
import com.apollographql.apollo.api.internal.UnmodifiableMapBuilder;
import com.apollographql.apollo.api.internal.Utils;

import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;

import okio.Buffer;
import okio.BufferedSource;
import okio.ByteString;

import org.jetbrains.annotations.NotNull;

public final class ChangeUserPasswordMutation implements Mutation<ChangeUserPasswordMutation.Data, ChangeUserPasswordMutation.Data, ChangeUserPasswordMutation.Variables> {
    public static final String OPERATION_ID = "1046292aeb1c3126e6715e003d7c278ec317ac55d7c9fe1362b854aa834db3b8";

    public static final String QUERY_DOCUMENT = QueryDocumentMinifier.minify(
            "mutation changeUserPassword($oldPassword: String!, $newPassword: String!) {\n"
                    + "  changeUserPassword(old_password: $oldPassword, new_password: $newPassword)\n"
                    + "}"
    );

    public static final OperationName OPERATION_NAME = new OperationName() {
        @Override
        public String name() {
            return "changeUserPassword";
        }
    };

    private final ChangeUserPasswordMutation.Variables variables;

    public ChangeUserPasswordMutation(@NotNull String oldPassword, @NotNull String newPassword) {
        Utils.checkNotNull(oldPassword, "oldPassword == null");
        Utils.checkNotNull(newPassword, "newPassword == null");
        variables = new ChangeUserPasswordMutation.Variables(oldPassword, newPassword);
    }

    @Override
    public String operationId() {
        return OPERATION_ID;
    }

    @Override
    public String queryDocument() {
        return QUERY_DOCUMENT;
    }

    @Override
    public ChangeUserPasswordMutation.Data wrapData(ChangeUserPasswordMutation.Data data) {
        return data;
    }

    @Override
    public ChangeUserPasswordMutation.Variables variables() {
        return variables;
    }

    @Override
    public ResponseFieldMapper<ChangeUserPasswordMutation.Data> responseFieldMapper() {
        return new Data.Mapper();
    }

    public static Builder builder() {
        return new Builder();
    }

    @Override
    public OperationName name() {
        return OPERATION_NAME;
    }

    @Override
    @NotNull
    public Response<ChangeUserPasswordMutation.Data> parse(@NotNull final BufferedSource source,
                                                           @NotNull final ScalarTypeAdapters scalarTypeAdapters) throws IOException {
        return SimpleOperationResponseParser.parse(source, this, scalarTypeAdapters);
    }

    @Override
    @NotNull
    public Response<ChangeUserPasswordMutation.Data> parse(@NotNull final ByteString byteString,
                                                           @NotNull final ScalarTypeAdapters scalarTypeAdapters) throws IOException {
        return parse(new Buffer().write(byteString), scalarTypeAdapters);
    }

    @Override
    @NotNull
    public Response<ChangeUserPasswordMutation.Data> parse(@NotNull final BufferedSource source)
            throws IOException {
        return parse(source, ScalarTypeAdapters.DEFAULT);
    }

    @Override
    @NotNull
    public Response<ChangeUserPasswordMutation.Data> parse(@NotNull final ByteString byteString)
            throws IOException {
        return parse(byteString, ScalarTypeAdapters.DEFAULT);
    }

    @Override
    @NotNull
    public ByteString composeRequestBody(@NotNull final ScalarTypeAdapters scalarTypeAdapters) {
        return OperationRequestBodyComposer.compose(this, false, true, scalarTypeAdapters);
    }

    @NotNull
    @Override
    public ByteString composeRequestBody() {
        return OperationRequestBodyComposer.compose(this, false, true, ScalarTypeAdapters.DEFAULT);
    }

    @Override
    @NotNull
    public ByteString composeRequestBody(final boolean autoPersistQueries,
                                         final boolean withQueryDocument, @NotNull final ScalarTypeAdapters scalarTypeAdapters) {
        return OperationRequestBodyComposer.compose(this, autoPersistQueries, withQueryDocument, scalarTypeAdapters);
    }

    public static final class Builder {
        private @NotNull
        String oldPassword;

        private @NotNull
        String newPassword;

        Builder() {
        }

        public Builder oldPassword(@NotNull String oldPassword) {
            this.oldPassword = oldPassword;
            return this;
        }

        public Builder newPassword(@NotNull String newPassword) {
            this.newPassword = newPassword;
            return this;
        }

        public ChangeUserPasswordMutation build() {
            Utils.checkNotNull(oldPassword, "oldPassword == null");
            Utils.checkNotNull(newPassword, "newPassword == null");
            return new ChangeUserPasswordMutation(oldPassword, newPassword);
        }
    }

    public static final class Variables extends Operation.Variables {
        private final @NotNull
        String oldPassword;

        private final @NotNull
        String newPassword;

        private final transient Map<String, Object> valueMap = new LinkedHashMap<>();

        Variables(@NotNull String oldPassword, @NotNull String newPassword) {
            this.oldPassword = oldPassword;
            this.newPassword = newPassword;
            this.valueMap.put("oldPassword", oldPassword);
            this.valueMap.put("newPassword", newPassword);
        }

        public @NotNull
        String oldPassword() {
            return oldPassword;
        }

        public @NotNull
        String newPassword() {
            return newPassword;
        }

        @Override
        public Map<String, Object> valueMap() {
            return Collections.unmodifiableMap(valueMap);
        }

        @Override
        public InputFieldMarshaller marshaller() {
            return new InputFieldMarshaller() {
                @Override
                public void marshal(InputFieldWriter writer) throws IOException {
                    writer.writeString("oldPassword", oldPassword);
                    writer.writeString("newPassword", newPassword);
                }
            };
        }
    }

    /**
     * Data from the response after executing this GraphQL operation
     */
    public static class Data implements Operation.Data {
        static final ResponseField[] $responseFields = {
                ResponseField.forString("changeUserPassword", "changeUserPassword", new UnmodifiableMapBuilder<String, Object>(2)
                        .put("old_password", new UnmodifiableMapBuilder<String, Object>(2)
                                .put("kind", "Variable")
                                .put("variableName", "oldPassword")
                                .build())
                        .put("new_password", new UnmodifiableMapBuilder<String, Object>(2)
                                .put("kind", "Variable")
                                .put("variableName", "newPassword")
                                .build())
                        .build(), false, Collections.<ResponseField.Condition>emptyList())
        };

        final @NotNull
        String changeUserPassword;

        private transient volatile String $toString;

        private transient volatile int $hashCode;

        private transient volatile boolean $hashCodeMemoized;

        public Data(@NotNull String changeUserPassword) {
            this.changeUserPassword = Utils.checkNotNull(changeUserPassword, "changeUserPassword == null");
        }

        public @NotNull
        String changeUserPassword() {
            return this.changeUserPassword;
        }

        @SuppressWarnings({"rawtypes", "unchecked"})
        public ResponseFieldMarshaller marshaller() {
            return new ResponseFieldMarshaller() {
                @Override
                public void marshal(ResponseWriter writer) {
                    writer.writeString($responseFields[0], changeUserPassword);
                }
            };
        }

        @Override
        public String toString() {
            if ($toString == null) {
                $toString = "Data{"
                        + "changeUserPassword=" + changeUserPassword
                        + "}";
            }
            return $toString;
        }

        @Override
        public boolean equals(Object o) {
            if (o == this) {
                return true;
            }
            if (o instanceof Data) {
                Data that = (Data) o;
                return this.changeUserPassword.equals(that.changeUserPassword);
            }
            return false;
        }

        @Override
        public int hashCode() {
            if (!$hashCodeMemoized) {
                int h = 1;
                h *= 1000003;
                h ^= changeUserPassword.hashCode();
                $hashCode = h;
                $hashCodeMemoized = true;
            }
            return $hashCode;
        }

        public static final class Mapper implements ResponseFieldMapper<Data> {
            @Override
            public Data map(ResponseReader reader) {
                final String changeUserPassword = reader.readString($responseFields[0]);
                return new Data(changeUserPassword);
            }
        }
    }
}