package com.xeniac.warrantyrostermanager.mainactivity.editwarrantyfragment;// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL plugin from the GraphQL queries it found.
// It should not be modified by hand.
//

import com.apollographql.apollo.api.Mutation;
import com.apollographql.apollo.api.Operation;
import com.apollographql.apollo.api.OperationName;
import com.apollographql.apollo.api.Response;
import com.apollographql.apollo.api.ResponseField;
import com.apollographql.apollo.api.ScalarTypeAdapters;
import com.apollographql.apollo.api.internal.InputFieldMarshaller;
import com.apollographql.apollo.api.internal.InputFieldWriter;
import com.apollographql.apollo.api.internal.OperationRequestBodyComposer;
import com.apollographql.apollo.api.internal.QueryDocumentMinifier;
import com.apollographql.apollo.api.internal.ResponseFieldMapper;
import com.apollographql.apollo.api.internal.ResponseFieldMarshaller;
import com.apollographql.apollo.api.internal.ResponseReader;
import com.apollographql.apollo.api.internal.ResponseWriter;
import com.apollographql.apollo.api.internal.SimpleOperationResponseParser;
import com.apollographql.apollo.api.internal.UnmodifiableMapBuilder;
import com.apollographql.apollo.api.internal.Utils;
import com.xeniac.warrantyrostermanager.CustomType;

import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;

import okio.Buffer;
import okio.BufferedSource;
import okio.ByteString;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

public final class EditWarrantyMutation implements Mutation<EditWarrantyMutation.Data, EditWarrantyMutation.Data, EditWarrantyMutation.Variables> {
    public static final String OPERATION_ID = "0d065586881c51631820a212dfd7d17a8115f5b1c391b27dca6f99375ca501bf";

    public static final String QUERY_DOCUMENT = QueryDocumentMinifier.minify(
            "mutation editWarranty($id: ID!, $warranty: EditWarrantyInput!) {\n"
                    + "  editWarranty(id: $id, input: $warranty) {\n"
                    + "    __typename\n"
                    + "    id\n"
                    + "    title\n"
                    + "    brand\n"
                    + "    model\n"
                    + "    serial_number\n"
                    + "    starting_date\n"
                    + "    expiry_date\n"
                    + "    description\n"
                    + "    category_id\n"
                    + "  }\n"
                    + "}"
    );

    public static final OperationName OPERATION_NAME = new OperationName() {
        @Override
        public String name() {
            return "editWarranty";
        }
    };

    private final EditWarrantyMutation.Variables variables;

    public EditWarrantyMutation(@NotNull String id, @NotNull EditWarrantyInput warranty) {
        Utils.checkNotNull(id, "id == null");
        Utils.checkNotNull(warranty, "warranty == null");
        variables = new EditWarrantyMutation.Variables(id, warranty);
    }

    @Override
    public String operationId() {
        return OPERATION_ID;
    }

    @Override
    public String queryDocument() {
        return QUERY_DOCUMENT;
    }

    @Override
    public EditWarrantyMutation.Data wrapData(EditWarrantyMutation.Data data) {
        return data;
    }

    @Override
    public EditWarrantyMutation.Variables variables() {
        return variables;
    }

    @Override
    public ResponseFieldMapper<EditWarrantyMutation.Data> responseFieldMapper() {
        return new Data.Mapper();
    }

    public static Builder builder() {
        return new Builder();
    }

    @Override
    public OperationName name() {
        return OPERATION_NAME;
    }

    @Override
    @NotNull
    public Response<EditWarrantyMutation.Data> parse(@NotNull final BufferedSource source,
                                                     @NotNull final ScalarTypeAdapters scalarTypeAdapters) throws IOException {
        return SimpleOperationResponseParser.parse(source, this, scalarTypeAdapters);
    }

    @Override
    @NotNull
    public Response<EditWarrantyMutation.Data> parse(@NotNull final ByteString byteString,
                                                     @NotNull final ScalarTypeAdapters scalarTypeAdapters) throws IOException {
        return parse(new Buffer().write(byteString), scalarTypeAdapters);
    }

    @Override
    @NotNull
    public Response<EditWarrantyMutation.Data> parse(@NotNull final BufferedSource source) throws
            IOException {
        return parse(source, ScalarTypeAdapters.DEFAULT);
    }

    @Override
    @NotNull
    public Response<EditWarrantyMutation.Data> parse(@NotNull final ByteString byteString) throws
            IOException {
        return parse(byteString, ScalarTypeAdapters.DEFAULT);
    }

    @Override
    @NotNull
    public ByteString composeRequestBody(@NotNull final ScalarTypeAdapters scalarTypeAdapters) {
        return OperationRequestBodyComposer.compose(this, false, true, scalarTypeAdapters);
    }

    @NotNull
    @Override
    public ByteString composeRequestBody() {
        return OperationRequestBodyComposer.compose(this, false, true, ScalarTypeAdapters.DEFAULT);
    }

    @Override
    @NotNull
    public ByteString composeRequestBody(final boolean autoPersistQueries,
                                         final boolean withQueryDocument, @NotNull final ScalarTypeAdapters scalarTypeAdapters) {
        return OperationRequestBodyComposer.compose(this, autoPersistQueries, withQueryDocument, scalarTypeAdapters);
    }

    public static final class Builder {
        private @NotNull
        String id;

        private @NotNull
        EditWarrantyInput warranty;

        Builder() {
        }

        public Builder id(@NotNull String id) {
            this.id = id;
            return this;
        }

        public Builder warranty(@NotNull EditWarrantyInput warranty) {
            this.warranty = warranty;
            return this;
        }

        public EditWarrantyMutation build() {
            Utils.checkNotNull(id, "id == null");
            Utils.checkNotNull(warranty, "warranty == null");
            return new EditWarrantyMutation(id, warranty);
        }
    }

    public static final class Variables extends Operation.Variables {
        private final @NotNull
        String id;

        private final @NotNull
        EditWarrantyInput warranty;

        private final transient Map<String, Object> valueMap = new LinkedHashMap<>();

        Variables(@NotNull String id, @NotNull EditWarrantyInput warranty) {
            this.id = id;
            this.warranty = warranty;
            this.valueMap.put("id", id);
            this.valueMap.put("warranty", warranty);
        }

        public @NotNull
        String id() {
            return id;
        }

        public @NotNull
        EditWarrantyInput warranty() {
            return warranty;
        }

        @Override
        public Map<String, Object> valueMap() {
            return Collections.unmodifiableMap(valueMap);
        }

        @Override
        public InputFieldMarshaller marshaller() {
            return new InputFieldMarshaller() {
                @Override
                public void marshal(InputFieldWriter writer) throws IOException {
                    writer.writeCustom("id", CustomType.ID, id);
                    writer.writeObject("warranty", warranty.marshaller());
                }
            };
        }
    }

    /**
     * Data from the response after executing this GraphQL operation
     */
    public static class Data implements Operation.Data {
        static final ResponseField[] $responseFields = {
                ResponseField.forObject("editWarranty", "editWarranty", new UnmodifiableMapBuilder<String, Object>(2)
                        .put("id", new UnmodifiableMapBuilder<String, Object>(2)
                                .put("kind", "Variable")
                                .put("variableName", "id")
                                .build())
                        .put("input", new UnmodifiableMapBuilder<String, Object>(2)
                                .put("kind", "Variable")
                                .put("variableName", "warranty")
                                .build())
                        .build(), false, Collections.<ResponseField.Condition>emptyList())
        };

        final @NotNull
        EditWarranty editWarranty;

        private transient volatile String $toString;

        private transient volatile int $hashCode;

        private transient volatile boolean $hashCodeMemoized;

        public Data(@NotNull EditWarranty editWarranty) {
            this.editWarranty = Utils.checkNotNull(editWarranty, "editWarranty == null");
        }

        public @NotNull
        EditWarranty editWarranty() {
            return this.editWarranty;
        }

        @SuppressWarnings({"rawtypes", "unchecked"})
        public ResponseFieldMarshaller marshaller() {
            return new ResponseFieldMarshaller() {
                @Override
                public void marshal(ResponseWriter writer) {
                    writer.writeObject($responseFields[0], editWarranty.marshaller());
                }
            };
        }

        @Override
        public String toString() {
            if ($toString == null) {
                $toString = "Data{"
                        + "editWarranty=" + editWarranty
                        + "}";
            }
            return $toString;
        }

        @Override
        public boolean equals(Object o) {
            if (o == this) {
                return true;
            }
            if (o instanceof Data) {
                Data that = (Data) o;
                return this.editWarranty.equals(that.editWarranty);
            }
            return false;
        }

        @Override
        public int hashCode() {
            if (!$hashCodeMemoized) {
                int h = 1;
                h *= 1000003;
                h ^= editWarranty.hashCode();
                $hashCode = h;
                $hashCodeMemoized = true;
            }
            return $hashCode;
        }

        public static final class Mapper implements ResponseFieldMapper<Data> {
            final EditWarranty.Mapper editWarrantyFieldMapper = new EditWarranty.Mapper();

            @Override
            public Data map(ResponseReader reader) {
                final EditWarranty editWarranty = reader.readObject($responseFields[0], new ResponseReader.ObjectReader<EditWarranty>() {
                    @Override
                    public EditWarranty read(ResponseReader reader) {
                        return editWarrantyFieldMapper.map(reader);
                    }
                });
                return new Data(editWarranty);
            }
        }
    }

    public static class EditWarranty {
        static final ResponseField[] $responseFields = {
                ResponseField.forString("__typename", "__typename", null, false, Collections.<ResponseField.Condition>emptyList()),
                ResponseField.forCustomType("id", "id", null, false, CustomType.ID, Collections.<ResponseField.Condition>emptyList()),
                ResponseField.forString("title", "title", null, false, Collections.<ResponseField.Condition>emptyList()),
                ResponseField.forString("brand", "brand", null, true, Collections.<ResponseField.Condition>emptyList()),
                ResponseField.forString("model", "model", null, true, Collections.<ResponseField.Condition>emptyList()),
                ResponseField.forString("serial_number", "serial_number", null, true, Collections.<ResponseField.Condition>emptyList()),
                ResponseField.forCustomType("starting_date", "starting_date", null, false, CustomType.DATE, Collections.<ResponseField.Condition>emptyList()),
                ResponseField.forCustomType("expiry_date", "expiry_date", null, false, CustomType.DATE, Collections.<ResponseField.Condition>emptyList()),
                ResponseField.forString("description", "description", null, true, Collections.<ResponseField.Condition>emptyList()),
                ResponseField.forCustomType("category_id", "category_id", null, true, CustomType.ID, Collections.<ResponseField.Condition>emptyList())
        };

        final @NotNull
        String __typename;

        final @NotNull
        String id;

        final @NotNull
        String title;

        final @Nullable
        String brand;

        final @Nullable
        String model;

        final @Nullable
        String serial_number;

        final @NotNull
        Object starting_date;

        final @NotNull
        Object expiry_date;

        final @Nullable
        String description;

        final @Nullable
        String category_id;

        private transient volatile String $toString;

        private transient volatile int $hashCode;

        private transient volatile boolean $hashCodeMemoized;

        public EditWarranty(@NotNull String __typename, @NotNull String id, @NotNull String title,
                            @Nullable String brand, @Nullable String model, @Nullable String serial_number,
                            @NotNull Object starting_date, @NotNull Object expiry_date, @Nullable String description,
                            @Nullable String category_id) {
            this.__typename = Utils.checkNotNull(__typename, "__typename == null");
            this.id = Utils.checkNotNull(id, "id == null");
            this.title = Utils.checkNotNull(title, "title == null");
            this.brand = brand;
            this.model = model;
            this.serial_number = serial_number;
            this.starting_date = Utils.checkNotNull(starting_date, "starting_date == null");
            this.expiry_date = Utils.checkNotNull(expiry_date, "expiry_date == null");
            this.description = description;
            this.category_id = category_id;
        }

        public @NotNull
        String __typename() {
            return this.__typename;
        }

        public @NotNull
        String id() {
            return this.id;
        }

        public @NotNull
        String title() {
            return this.title;
        }

        public @Nullable
        String brand() {
            return this.brand;
        }

        public @Nullable
        String model() {
            return this.model;
        }

        public @Nullable
        String serial_number() {
            return this.serial_number;
        }

        public @NotNull
        Object starting_date() {
            return this.starting_date;
        }

        public @NotNull
        Object expiry_date() {
            return this.expiry_date;
        }

        public @Nullable
        String description() {
            return this.description;
        }

        public @Nullable
        String category_id() {
            return this.category_id;
        }

        @SuppressWarnings({"rawtypes", "unchecked"})
        public ResponseFieldMarshaller marshaller() {
            return new ResponseFieldMarshaller() {
                @Override
                public void marshal(ResponseWriter writer) {
                    writer.writeString($responseFields[0], __typename);
                    writer.writeCustom((ResponseField.CustomTypeField) $responseFields[1], id);
                    writer.writeString($responseFields[2], title);
                    writer.writeString($responseFields[3], brand);
                    writer.writeString($responseFields[4], model);
                    writer.writeString($responseFields[5], serial_number);
                    writer.writeCustom((ResponseField.CustomTypeField) $responseFields[6], starting_date);
                    writer.writeCustom((ResponseField.CustomTypeField) $responseFields[7], expiry_date);
                    writer.writeString($responseFields[8], description);
                    writer.writeCustom((ResponseField.CustomTypeField) $responseFields[9], category_id);
                }
            };
        }

        @Override
        public String toString() {
            if ($toString == null) {
                $toString = "EditWarranty{"
                        + "__typename=" + __typename + ", "
                        + "id=" + id + ", "
                        + "title=" + title + ", "
                        + "brand=" + brand + ", "
                        + "model=" + model + ", "
                        + "serial_number=" + serial_number + ", "
                        + "starting_date=" + starting_date + ", "
                        + "expiry_date=" + expiry_date + ", "
                        + "description=" + description + ", "
                        + "category_id=" + category_id
                        + "}";
            }
            return $toString;
        }

        @Override
        public boolean equals(Object o) {
            if (o == this) {
                return true;
            }
            if (o instanceof EditWarranty) {
                EditWarranty that = (EditWarranty) o;
                return this.__typename.equals(that.__typename)
                        && this.id.equals(that.id)
                        && this.title.equals(that.title)
                        && ((this.brand == null) ? (that.brand == null) : this.brand.equals(that.brand))
                        && ((this.model == null) ? (that.model == null) : this.model.equals(that.model))
                        && ((this.serial_number == null) ? (that.serial_number == null) : this.serial_number.equals(that.serial_number))
                        && this.starting_date.equals(that.starting_date)
                        && this.expiry_date.equals(that.expiry_date)
                        && ((this.description == null) ? (that.description == null) : this.description.equals(that.description))
                        && ((this.category_id == null) ? (that.category_id == null) : this.category_id.equals(that.category_id));
            }
            return false;
        }

        @Override
        public int hashCode() {
            if (!$hashCodeMemoized) {
                int h = 1;
                h *= 1000003;
                h ^= __typename.hashCode();
                h *= 1000003;
                h ^= id.hashCode();
                h *= 1000003;
                h ^= title.hashCode();
                h *= 1000003;
                h ^= (brand == null) ? 0 : brand.hashCode();
                h *= 1000003;
                h ^= (model == null) ? 0 : model.hashCode();
                h *= 1000003;
                h ^= (serial_number == null) ? 0 : serial_number.hashCode();
                h *= 1000003;
                h ^= starting_date.hashCode();
                h *= 1000003;
                h ^= expiry_date.hashCode();
                h *= 1000003;
                h ^= (description == null) ? 0 : description.hashCode();
                h *= 1000003;
                h ^= (category_id == null) ? 0 : category_id.hashCode();
                $hashCode = h;
                $hashCodeMemoized = true;
            }
            return $hashCode;
        }

        public static final class Mapper implements ResponseFieldMapper<EditWarranty> {
            @Override
            public EditWarranty map(ResponseReader reader) {
                final String __typename = reader.readString($responseFields[0]);
                final String id = reader.readCustomType((ResponseField.CustomTypeField) $responseFields[1]);
                final String title = reader.readString($responseFields[2]);
                final String brand = reader.readString($responseFields[3]);
                final String model = reader.readString($responseFields[4]);
                final String serial_number = reader.readString($responseFields[5]);
                final Object starting_date = reader.readCustomType((ResponseField.CustomTypeField) $responseFields[6]);
                final Object expiry_date = reader.readCustomType((ResponseField.CustomTypeField) $responseFields[7]);
                final String description = reader.readString($responseFields[8]);
                final String category_id = reader.readCustomType((ResponseField.CustomTypeField) $responseFields[9]);
                return new EditWarranty(__typename, id, title, brand, model, serial_number, starting_date, expiry_date, description, category_id);
            }
        }
    }
}