package com.xeniac.warrantyrostermanager.landingactivity.registerfragment;// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL plugin from the GraphQL queries it found.
// It should not be modified by hand.
//

import com.apollographql.apollo.api.Mutation;
import com.apollographql.apollo.api.Operation;
import com.apollographql.apollo.api.OperationName;
import com.apollographql.apollo.api.Response;
import com.apollographql.apollo.api.ResponseField;
import com.apollographql.apollo.api.ScalarTypeAdapters;
import com.apollographql.apollo.api.internal.InputFieldMarshaller;
import com.apollographql.apollo.api.internal.InputFieldWriter;
import com.apollographql.apollo.api.internal.OperationRequestBodyComposer;
import com.apollographql.apollo.api.internal.QueryDocumentMinifier;
import com.apollographql.apollo.api.internal.ResponseFieldMapper;
import com.apollographql.apollo.api.internal.ResponseFieldMarshaller;
import com.apollographql.apollo.api.internal.ResponseReader;
import com.apollographql.apollo.api.internal.ResponseWriter;
import com.apollographql.apollo.api.internal.SimpleOperationResponseParser;
import com.apollographql.apollo.api.internal.UnmodifiableMapBuilder;
import com.apollographql.apollo.api.internal.Utils;

import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;

import okio.Buffer;
import okio.BufferedSource;
import okio.ByteString;

import org.jetbrains.annotations.NotNull;

public final class RegisterViaEmailMutation implements Mutation<RegisterViaEmailMutation.Data, RegisterViaEmailMutation.Data, RegisterViaEmailMutation.Variables> {
    public static final String OPERATION_ID = "2c990b27f4b6b3a5cc10d602736f39025778486a8bb509db7d45616f79880689";

    public static final String QUERY_DOCUMENT = QueryDocumentMinifier.minify(
            "mutation registerViaEmail($email: String!, $password: String!, $deviceName: String!) {\n"
                    + "  registerViaEmail(email: $email, password: $password, device_name: $deviceName) {\n"
                    + "    __typename\n"
                    + "    token\n"
                    + "  }\n"
                    + "}"
    );

    public static final OperationName OPERATION_NAME = new OperationName() {
        @Override
        public String name() {
            return "registerViaEmail";
        }
    };

    private final RegisterViaEmailMutation.Variables variables;

    public RegisterViaEmailMutation(@NotNull String email, @NotNull String password,
                                    @NotNull String deviceName) {
        Utils.checkNotNull(email, "email == null");
        Utils.checkNotNull(password, "password == null");
        Utils.checkNotNull(deviceName, "deviceName == null");
        variables = new RegisterViaEmailMutation.Variables(email, password, deviceName);
    }

    @Override
    public String operationId() {
        return OPERATION_ID;
    }

    @Override
    public String queryDocument() {
        return QUERY_DOCUMENT;
    }

    @Override
    public RegisterViaEmailMutation.Data wrapData(RegisterViaEmailMutation.Data data) {
        return data;
    }

    @Override
    public RegisterViaEmailMutation.Variables variables() {
        return variables;
    }

    @Override
    public ResponseFieldMapper<RegisterViaEmailMutation.Data> responseFieldMapper() {
        return new Data.Mapper();
    }

    public static Builder builder() {
        return new Builder();
    }

    @Override
    public OperationName name() {
        return OPERATION_NAME;
    }

    @Override
    @NotNull
    public Response<RegisterViaEmailMutation.Data> parse(@NotNull final BufferedSource source,
                                                         @NotNull final ScalarTypeAdapters scalarTypeAdapters) throws IOException {
        return SimpleOperationResponseParser.parse(source, this, scalarTypeAdapters);
    }

    @Override
    @NotNull
    public Response<RegisterViaEmailMutation.Data> parse(@NotNull final ByteString byteString,
                                                         @NotNull final ScalarTypeAdapters scalarTypeAdapters) throws IOException {
        return parse(new Buffer().write(byteString), scalarTypeAdapters);
    }

    @Override
    @NotNull
    public Response<RegisterViaEmailMutation.Data> parse(@NotNull final BufferedSource source) throws
            IOException {
        return parse(source, ScalarTypeAdapters.DEFAULT);
    }

    @Override
    @NotNull
    public Response<RegisterViaEmailMutation.Data> parse(@NotNull final ByteString byteString) throws
            IOException {
        return parse(byteString, ScalarTypeAdapters.DEFAULT);
    }

    @Override
    @NotNull
    public ByteString composeRequestBody(@NotNull final ScalarTypeAdapters scalarTypeAdapters) {
        return OperationRequestBodyComposer.compose(this, false, true, scalarTypeAdapters);
    }

    @NotNull
    @Override
    public ByteString composeRequestBody() {
        return OperationRequestBodyComposer.compose(this, false, true, ScalarTypeAdapters.DEFAULT);
    }

    @Override
    @NotNull
    public ByteString composeRequestBody(final boolean autoPersistQueries,
                                         final boolean withQueryDocument, @NotNull final ScalarTypeAdapters scalarTypeAdapters) {
        return OperationRequestBodyComposer.compose(this, autoPersistQueries, withQueryDocument, scalarTypeAdapters);
    }

    public static final class Builder {
        private @NotNull
        String email;

        private @NotNull
        String password;

        private @NotNull
        String deviceName;

        Builder() {
        }

        public Builder email(@NotNull String email) {
            this.email = email;
            return this;
        }

        public Builder password(@NotNull String password) {
            this.password = password;
            return this;
        }

        public Builder deviceName(@NotNull String deviceName) {
            this.deviceName = deviceName;
            return this;
        }

        public RegisterViaEmailMutation build() {
            Utils.checkNotNull(email, "email == null");
            Utils.checkNotNull(password, "password == null");
            Utils.checkNotNull(deviceName, "deviceName == null");
            return new RegisterViaEmailMutation(email, password, deviceName);
        }
    }

    public static final class Variables extends Operation.Variables {
        private final @NotNull
        String email;

        private final @NotNull
        String password;

        private final @NotNull
        String deviceName;

        private final transient Map<String, Object> valueMap = new LinkedHashMap<>();

        Variables(@NotNull String email, @NotNull String password, @NotNull String deviceName) {
            this.email = email;
            this.password = password;
            this.deviceName = deviceName;
            this.valueMap.put("email", email);
            this.valueMap.put("password", password);
            this.valueMap.put("deviceName", deviceName);
        }

        public @NotNull
        String email() {
            return email;
        }

        public @NotNull
        String password() {
            return password;
        }

        public @NotNull
        String deviceName() {
            return deviceName;
        }

        @Override
        public Map<String, Object> valueMap() {
            return Collections.unmodifiableMap(valueMap);
        }

        @Override
        public InputFieldMarshaller marshaller() {
            return new InputFieldMarshaller() {
                @Override
                public void marshal(InputFieldWriter writer) throws IOException {
                    writer.writeString("email", email);
                    writer.writeString("password", password);
                    writer.writeString("deviceName", deviceName);
                }
            };
        }
    }

    /**
     * Data from the response after executing this GraphQL operation
     */
    public static class Data implements Operation.Data {
        static final ResponseField[] $responseFields = {
                ResponseField.forObject("registerViaEmail", "registerViaEmail", new UnmodifiableMapBuilder<String, Object>(3)
                        .put("email", new UnmodifiableMapBuilder<String, Object>(2)
                                .put("kind", "Variable")
                                .put("variableName", "email")
                                .build())
                        .put("password", new UnmodifiableMapBuilder<String, Object>(2)
                                .put("kind", "Variable")
                                .put("variableName", "password")
                                .build())
                        .put("device_name", new UnmodifiableMapBuilder<String, Object>(2)
                                .put("kind", "Variable")
                                .put("variableName", "deviceName")
                                .build())
                        .build(), false, Collections.<ResponseField.Condition>emptyList())
        };

        final @NotNull
        RegisterViaEmail registerViaEmail;

        private transient volatile String $toString;

        private transient volatile int $hashCode;

        private transient volatile boolean $hashCodeMemoized;

        public Data(@NotNull RegisterViaEmail registerViaEmail) {
            this.registerViaEmail = Utils.checkNotNull(registerViaEmail, "registerViaEmail == null");
        }

        public @NotNull
        RegisterViaEmail registerViaEmail() {
            return this.registerViaEmail;
        }

        @SuppressWarnings({"rawtypes", "unchecked"})
        public ResponseFieldMarshaller marshaller() {
            return new ResponseFieldMarshaller() {
                @Override
                public void marshal(ResponseWriter writer) {
                    writer.writeObject($responseFields[0], registerViaEmail.marshaller());
                }
            };
        }

        @Override
        public String toString() {
            if ($toString == null) {
                $toString = "Data{"
                        + "registerViaEmail=" + registerViaEmail
                        + "}";
            }
            return $toString;
        }

        @Override
        public boolean equals(Object o) {
            if (o == this) {
                return true;
            }
            if (o instanceof Data) {
                Data that = (Data) o;
                return this.registerViaEmail.equals(that.registerViaEmail);
            }
            return false;
        }

        @Override
        public int hashCode() {
            if (!$hashCodeMemoized) {
                int h = 1;
                h *= 1000003;
                h ^= registerViaEmail.hashCode();
                $hashCode = h;
                $hashCodeMemoized = true;
            }
            return $hashCode;
        }

        public static final class Mapper implements ResponseFieldMapper<Data> {
            final RegisterViaEmail.Mapper registerViaEmailFieldMapper = new RegisterViaEmail.Mapper();

            @Override
            public Data map(ResponseReader reader) {
                final RegisterViaEmail registerViaEmail = reader.readObject($responseFields[0], new ResponseReader.ObjectReader<RegisterViaEmail>() {
                    @Override
                    public RegisterViaEmail read(ResponseReader reader) {
                        return registerViaEmailFieldMapper.map(reader);
                    }
                });
                return new Data(registerViaEmail);
            }
        }
    }

    public static class RegisterViaEmail {
        static final ResponseField[] $responseFields = {
                ResponseField.forString("__typename", "__typename", null, false, Collections.<ResponseField.Condition>emptyList()),
                ResponseField.forString("token", "token", null, false, Collections.<ResponseField.Condition>emptyList())
        };

        final @NotNull
        String __typename;

        final @NotNull
        String token;

        private transient volatile String $toString;

        private transient volatile int $hashCode;

        private transient volatile boolean $hashCodeMemoized;

        public RegisterViaEmail(@NotNull String __typename, @NotNull String token) {
            this.__typename = Utils.checkNotNull(__typename, "__typename == null");
            this.token = Utils.checkNotNull(token, "token == null");
        }

        public @NotNull
        String __typename() {
            return this.__typename;
        }

        public @NotNull
        String token() {
            return this.token;
        }

        @SuppressWarnings({"rawtypes", "unchecked"})
        public ResponseFieldMarshaller marshaller() {
            return new ResponseFieldMarshaller() {
                @Override
                public void marshal(ResponseWriter writer) {
                    writer.writeString($responseFields[0], __typename);
                    writer.writeString($responseFields[1], token);
                }
            };
        }

        @Override
        public String toString() {
            if ($toString == null) {
                $toString = "RegisterViaEmail{"
                        + "__typename=" + __typename + ", "
                        + "token=" + token
                        + "}";
            }
            return $toString;
        }

        @Override
        public boolean equals(Object o) {
            if (o == this) {
                return true;
            }
            if (o instanceof RegisterViaEmail) {
                RegisterViaEmail that = (RegisterViaEmail) o;
                return this.__typename.equals(that.__typename)
                        && this.token.equals(that.token);
            }
            return false;
        }

        @Override
        public int hashCode() {
            if (!$hashCodeMemoized) {
                int h = 1;
                h *= 1000003;
                h ^= __typename.hashCode();
                h *= 1000003;
                h ^= token.hashCode();
                $hashCode = h;
                $hashCodeMemoized = true;
            }
            return $hashCode;
        }

        public static final class Mapper implements ResponseFieldMapper<RegisterViaEmail> {
            @Override
            public RegisterViaEmail map(ResponseReader reader) {
                final String __typename = reader.readString($responseFields[0]);
                final String token = reader.readString($responseFields[1]);
                return new RegisterViaEmail(__typename, token);
            }
        }
    }
}