package com.xeniac.warrantyrostermanager.mainactivity.setingsfragment;// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL plugin from the GraphQL queries it found.
// It should not be modified by hand.
//

import com.apollographql.apollo.api.Operation;
import com.apollographql.apollo.api.OperationName;
import com.apollographql.apollo.api.Query;
import com.apollographql.apollo.api.Response;
import com.apollographql.apollo.api.ResponseField;
import com.apollographql.apollo.api.ScalarTypeAdapters;
import com.apollographql.apollo.api.internal.OperationRequestBodyComposer;
import com.apollographql.apollo.api.internal.QueryDocumentMinifier;
import com.apollographql.apollo.api.internal.ResponseFieldMapper;
import com.apollographql.apollo.api.internal.ResponseFieldMarshaller;
import com.apollographql.apollo.api.internal.ResponseReader;
import com.apollographql.apollo.api.internal.ResponseWriter;
import com.apollographql.apollo.api.internal.SimpleOperationResponseParser;
import com.apollographql.apollo.api.internal.Utils;

import java.io.IOException;
import java.lang.Boolean;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Collections;

import okio.Buffer;
import okio.BufferedSource;
import okio.ByteString;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

public final class GetAccountDetailsQuery implements Query<GetAccountDetailsQuery.Data, GetAccountDetailsQuery.Data, Operation.Variables> {
    public static final String OPERATION_ID = "eccd65cc812c668f43c763420f438d93ef438e1a0d2138bed7f80fcda6916256";

    public static final String QUERY_DOCUMENT = QueryDocumentMinifier.minify(
            "query getAccountDetails {\n"
                    + "  getAccountDetails {\n"
                    + "    __typename\n"
                    + "    email\n"
                    + "    is_email_verified\n"
                    + "  }\n"
                    + "}"
    );

    public static final OperationName OPERATION_NAME = new OperationName() {
        @Override
        public String name() {
            return "getAccountDetails";
        }
    };

    private final Operation.Variables variables;

    public GetAccountDetailsQuery() {
        this.variables = Operation.EMPTY_VARIABLES;
    }

    @Override
    public String operationId() {
        return OPERATION_ID;
    }

    @Override
    public String queryDocument() {
        return QUERY_DOCUMENT;
    }

    @Override
    public GetAccountDetailsQuery.Data wrapData(GetAccountDetailsQuery.Data data) {
        return data;
    }

    @Override
    public Operation.Variables variables() {
        return variables;
    }

    @Override
    public ResponseFieldMapper<GetAccountDetailsQuery.Data> responseFieldMapper() {
        return new Data.Mapper();
    }

    public static Builder builder() {
        return new Builder();
    }

    @Override
    public OperationName name() {
        return OPERATION_NAME;
    }

    @Override
    @NotNull
    public Response<GetAccountDetailsQuery.Data> parse(@NotNull final BufferedSource source,
                                                       @NotNull final ScalarTypeAdapters scalarTypeAdapters) throws IOException {
        return SimpleOperationResponseParser.parse(source, this, scalarTypeAdapters);
    }

    @Override
    @NotNull
    public Response<GetAccountDetailsQuery.Data> parse(@NotNull final ByteString byteString,
                                                       @NotNull final ScalarTypeAdapters scalarTypeAdapters) throws IOException {
        return parse(new Buffer().write(byteString), scalarTypeAdapters);
    }

    @Override
    @NotNull
    public Response<GetAccountDetailsQuery.Data> parse(@NotNull final BufferedSource source) throws
            IOException {
        return parse(source, ScalarTypeAdapters.DEFAULT);
    }

    @Override
    @NotNull
    public Response<GetAccountDetailsQuery.Data> parse(@NotNull final ByteString byteString) throws
            IOException {
        return parse(byteString, ScalarTypeAdapters.DEFAULT);
    }

    @Override
    @NotNull
    public ByteString composeRequestBody(@NotNull final ScalarTypeAdapters scalarTypeAdapters) {
        return OperationRequestBodyComposer.compose(this, false, true, scalarTypeAdapters);
    }

    @NotNull
    @Override
    public ByteString composeRequestBody() {
        return OperationRequestBodyComposer.compose(this, false, true, ScalarTypeAdapters.DEFAULT);
    }

    @Override
    @NotNull
    public ByteString composeRequestBody(final boolean autoPersistQueries,
                                         final boolean withQueryDocument, @NotNull final ScalarTypeAdapters scalarTypeAdapters) {
        return OperationRequestBodyComposer.compose(this, autoPersistQueries, withQueryDocument, scalarTypeAdapters);
    }

    public static final class Builder {
        Builder() {
        }

        public GetAccountDetailsQuery build() {
            return new GetAccountDetailsQuery();
        }
    }

    /**
     * Data from the response after executing this GraphQL operation
     */
    public static class Data implements Operation.Data {
        static final ResponseField[] $responseFields = {
                ResponseField.forObject("getAccountDetails", "getAccountDetails", null, false, Collections.<ResponseField.Condition>emptyList())
        };

        final @NotNull
        GetAccountDetails getAccountDetails;

        private transient volatile String $toString;

        private transient volatile int $hashCode;

        private transient volatile boolean $hashCodeMemoized;

        public Data(@NotNull GetAccountDetails getAccountDetails) {
            this.getAccountDetails = Utils.checkNotNull(getAccountDetails, "getAccountDetails == null");
        }

        public @NotNull
        GetAccountDetails getAccountDetails() {
            return this.getAccountDetails;
        }

        @SuppressWarnings({"rawtypes", "unchecked"})
        public ResponseFieldMarshaller marshaller() {
            return new ResponseFieldMarshaller() {
                @Override
                public void marshal(ResponseWriter writer) {
                    writer.writeObject($responseFields[0], getAccountDetails.marshaller());
                }
            };
        }

        @Override
        public String toString() {
            if ($toString == null) {
                $toString = "Data{"
                        + "getAccountDetails=" + getAccountDetails
                        + "}";
            }
            return $toString;
        }

        @Override
        public boolean equals(Object o) {
            if (o == this) {
                return true;
            }
            if (o instanceof Data) {
                Data that = (Data) o;
                return this.getAccountDetails.equals(that.getAccountDetails);
            }
            return false;
        }

        @Override
        public int hashCode() {
            if (!$hashCodeMemoized) {
                int h = 1;
                h *= 1000003;
                h ^= getAccountDetails.hashCode();
                $hashCode = h;
                $hashCodeMemoized = true;
            }
            return $hashCode;
        }

        public static final class Mapper implements ResponseFieldMapper<Data> {
            final GetAccountDetails.Mapper getAccountDetailsFieldMapper = new GetAccountDetails.Mapper();

            @Override
            public Data map(ResponseReader reader) {
                final GetAccountDetails getAccountDetails = reader.readObject($responseFields[0], new ResponseReader.ObjectReader<GetAccountDetails>() {
                    @Override
                    public GetAccountDetails read(ResponseReader reader) {
                        return getAccountDetailsFieldMapper.map(reader);
                    }
                });
                return new Data(getAccountDetails);
            }
        }
    }

    public static class GetAccountDetails {
        static final ResponseField[] $responseFields = {
                ResponseField.forString("__typename", "__typename", null, false, Collections.<ResponseField.Condition>emptyList()),
                ResponseField.forString("email", "email", null, false, Collections.<ResponseField.Condition>emptyList()),
                ResponseField.forBoolean("is_email_verified", "is_email_verified", null, true, Collections.<ResponseField.Condition>emptyList())
        };

        final @NotNull
        String __typename;

        final @NotNull
        String email;

        final @Nullable
        Boolean is_email_verified;

        private transient volatile String $toString;

        private transient volatile int $hashCode;

        private transient volatile boolean $hashCodeMemoized;

        public GetAccountDetails(@NotNull String __typename, @NotNull String email,
                                 @Nullable Boolean is_email_verified) {
            this.__typename = Utils.checkNotNull(__typename, "__typename == null");
            this.email = Utils.checkNotNull(email, "email == null");
            this.is_email_verified = is_email_verified;
        }

        public @NotNull
        String __typename() {
            return this.__typename;
        }

        public @NotNull
        String email() {
            return this.email;
        }

        public @Nullable
        Boolean is_email_verified() {
            return this.is_email_verified;
        }

        @SuppressWarnings({"rawtypes", "unchecked"})
        public ResponseFieldMarshaller marshaller() {
            return new ResponseFieldMarshaller() {
                @Override
                public void marshal(ResponseWriter writer) {
                    writer.writeString($responseFields[0], __typename);
                    writer.writeString($responseFields[1], email);
                    writer.writeBoolean($responseFields[2], is_email_verified);
                }
            };
        }

        @Override
        public String toString() {
            if ($toString == null) {
                $toString = "GetAccountDetails{"
                        + "__typename=" + __typename + ", "
                        + "email=" + email + ", "
                        + "is_email_verified=" + is_email_verified
                        + "}";
            }
            return $toString;
        }

        @Override
        public boolean equals(Object o) {
            if (o == this) {
                return true;
            }
            if (o instanceof GetAccountDetails) {
                GetAccountDetails that = (GetAccountDetails) o;
                return this.__typename.equals(that.__typename)
                        && this.email.equals(that.email)
                        && ((this.is_email_verified == null) ? (that.is_email_verified == null) : this.is_email_verified.equals(that.is_email_verified));
            }
            return false;
        }

        @Override
        public int hashCode() {
            if (!$hashCodeMemoized) {
                int h = 1;
                h *= 1000003;
                h ^= __typename.hashCode();
                h *= 1000003;
                h ^= email.hashCode();
                h *= 1000003;
                h ^= (is_email_verified == null) ? 0 : is_email_verified.hashCode();
                $hashCode = h;
                $hashCodeMemoized = true;
            }
            return $hashCode;
        }

        public static final class Mapper implements ResponseFieldMapper<GetAccountDetails> {
            @Override
            public GetAccountDetails map(ResponseReader reader) {
                final String __typename = reader.readString($responseFields[0]);
                final String email = reader.readString($responseFields[1]);
                final Boolean is_email_verified = reader.readBoolean($responseFields[2]);
                return new GetAccountDetails(__typename, email, is_email_verified);
            }
        }
    }
}