package com.xeniac.warrantyrostermanager.mainactivity.setingsfragment;// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL plugin from the GraphQL queries it found.
// It should not be modified by hand.
//

import com.apollographql.apollo.api.Mutation;
import com.apollographql.apollo.api.Operation;
import com.apollographql.apollo.api.OperationName;
import com.apollographql.apollo.api.Response;
import com.apollographql.apollo.api.ResponseField;
import com.apollographql.apollo.api.ScalarTypeAdapters;
import com.apollographql.apollo.api.internal.OperationRequestBodyComposer;
import com.apollographql.apollo.api.internal.QueryDocumentMinifier;
import com.apollographql.apollo.api.internal.ResponseFieldMapper;
import com.apollographql.apollo.api.internal.ResponseFieldMarshaller;
import com.apollographql.apollo.api.internal.ResponseReader;
import com.apollographql.apollo.api.internal.ResponseWriter;
import com.apollographql.apollo.api.internal.SimpleOperationResponseParser;
import com.apollographql.apollo.api.internal.Utils;

import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Collections;

import okio.Buffer;
import okio.BufferedSource;
import okio.ByteString;

import org.jetbrains.annotations.NotNull;

public final class SendVerificationEmailMutation implements Mutation<SendVerificationEmailMutation.Data, SendVerificationEmailMutation.Data, Operation.Variables> {
    public static final String OPERATION_ID = "20ea59c8342b613db5e527a9ea2b46a7bf8063348059fa7d3598bc04bb9f8f0d";

    public static final String QUERY_DOCUMENT = QueryDocumentMinifier.minify(
            "mutation sendVerificationEmail {\n"
                    + "  sendVerificationEmail\n"
                    + "}"
    );

    public static final OperationName OPERATION_NAME = new OperationName() {
        @Override
        public String name() {
            return "sendVerificationEmail";
        }
    };

    private final Operation.Variables variables;

    public SendVerificationEmailMutation() {
        this.variables = Operation.EMPTY_VARIABLES;
    }

    @Override
    public String operationId() {
        return OPERATION_ID;
    }

    @Override
    public String queryDocument() {
        return QUERY_DOCUMENT;
    }

    @Override
    public SendVerificationEmailMutation.Data wrapData(SendVerificationEmailMutation.Data data) {
        return data;
    }

    @Override
    public Operation.Variables variables() {
        return variables;
    }

    @Override
    public ResponseFieldMapper<SendVerificationEmailMutation.Data> responseFieldMapper() {
        return new Data.Mapper();
    }

    public static Builder builder() {
        return new Builder();
    }

    @Override
    public OperationName name() {
        return OPERATION_NAME;
    }

    @Override
    @NotNull
    public Response<SendVerificationEmailMutation.Data> parse(@NotNull final BufferedSource source,
                                                              @NotNull final ScalarTypeAdapters scalarTypeAdapters) throws IOException {
        return SimpleOperationResponseParser.parse(source, this, scalarTypeAdapters);
    }

    @Override
    @NotNull
    public Response<SendVerificationEmailMutation.Data> parse(@NotNull final ByteString byteString,
                                                              @NotNull final ScalarTypeAdapters scalarTypeAdapters) throws IOException {
        return parse(new Buffer().write(byteString), scalarTypeAdapters);
    }

    @Override
    @NotNull
    public Response<SendVerificationEmailMutation.Data> parse(@NotNull final BufferedSource source)
            throws IOException {
        return parse(source, ScalarTypeAdapters.DEFAULT);
    }

    @Override
    @NotNull
    public Response<SendVerificationEmailMutation.Data> parse(@NotNull final ByteString byteString)
            throws IOException {
        return parse(byteString, ScalarTypeAdapters.DEFAULT);
    }

    @Override
    @NotNull
    public ByteString composeRequestBody(@NotNull final ScalarTypeAdapters scalarTypeAdapters) {
        return OperationRequestBodyComposer.compose(this, false, true, scalarTypeAdapters);
    }

    @NotNull
    @Override
    public ByteString composeRequestBody() {
        return OperationRequestBodyComposer.compose(this, false, true, ScalarTypeAdapters.DEFAULT);
    }

    @Override
    @NotNull
    public ByteString composeRequestBody(final boolean autoPersistQueries,
                                         final boolean withQueryDocument, @NotNull final ScalarTypeAdapters scalarTypeAdapters) {
        return OperationRequestBodyComposer.compose(this, autoPersistQueries, withQueryDocument, scalarTypeAdapters);
    }

    public static final class Builder {
        Builder() {
        }

        public SendVerificationEmailMutation build() {
            return new SendVerificationEmailMutation();
        }
    }

    /**
     * Data from the response after executing this GraphQL operation
     */
    public static class Data implements Operation.Data {
        static final ResponseField[] $responseFields = {
                ResponseField.forString("sendVerificationEmail", "sendVerificationEmail", null, false, Collections.<ResponseField.Condition>emptyList())
        };

        final @NotNull
        String sendVerificationEmail;

        private transient volatile String $toString;

        private transient volatile int $hashCode;

        private transient volatile boolean $hashCodeMemoized;

        public Data(@NotNull String sendVerificationEmail) {
            this.sendVerificationEmail = Utils.checkNotNull(sendVerificationEmail, "sendVerificationEmail == null");
        }

        public @NotNull
        String sendVerificationEmail() {
            return this.sendVerificationEmail;
        }

        @SuppressWarnings({"rawtypes", "unchecked"})
        public ResponseFieldMarshaller marshaller() {
            return new ResponseFieldMarshaller() {
                @Override
                public void marshal(ResponseWriter writer) {
                    writer.writeString($responseFields[0], sendVerificationEmail);
                }
            };
        }

        @Override
        public String toString() {
            if ($toString == null) {
                $toString = "Data{"
                        + "sendVerificationEmail=" + sendVerificationEmail
                        + "}";
            }
            return $toString;
        }

        @Override
        public boolean equals(Object o) {
            if (o == this) {
                return true;
            }
            if (o instanceof Data) {
                Data that = (Data) o;
                return this.sendVerificationEmail.equals(that.sendVerificationEmail);
            }
            return false;
        }

        @Override
        public int hashCode() {
            if (!$hashCodeMemoized) {
                int h = 1;
                h *= 1000003;
                h ^= sendVerificationEmail.hashCode();
                $hashCode = h;
                $hashCodeMemoized = true;
            }
            return $hashCode;
        }

        public static final class Mapper implements ResponseFieldMapper<Data> {
            @Override
            public Data map(ResponseReader reader) {
                final String sendVerificationEmail = reader.readString($responseFields[0]);
                return new Data(sendVerificationEmail);
            }
        }
    }
}