package com.xeniac.warrantyrostermanager.mainactivity.warrantiesfragment;// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL plugin from the GraphQL queries it found.
// It should not be modified by hand.
//

import com.apollographql.apollo.api.Operation;
import com.apollographql.apollo.api.OperationName;
import com.apollographql.apollo.api.Query;
import com.apollographql.apollo.api.Response;
import com.apollographql.apollo.api.ResponseField;
import com.apollographql.apollo.api.ScalarTypeAdapters;
import com.apollographql.apollo.api.internal.OperationRequestBodyComposer;
import com.apollographql.apollo.api.internal.QueryDocumentMinifier;
import com.apollographql.apollo.api.internal.ResponseFieldMapper;
import com.apollographql.apollo.api.internal.ResponseFieldMarshaller;
import com.apollographql.apollo.api.internal.ResponseReader;
import com.apollographql.apollo.api.internal.ResponseWriter;
import com.apollographql.apollo.api.internal.SimpleOperationResponseParser;
import com.apollographql.apollo.api.internal.Utils;

import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Collections;
import java.util.List;

import okio.Buffer;
import okio.BufferedSource;
import okio.ByteString;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import com.xeniac.warrantyrostermanager.CustomType;

public final class GetWarrantiesListQuery implements Query<GetWarrantiesListQuery.Data, GetWarrantiesListQuery.Data, Operation.Variables> {
    public static final String OPERATION_ID = "f5cc120a34955ca05ea9c0d5187075304674ba3c2ea95bd5771a60bed05303ca";

    public static final String QUERY_DOCUMENT = QueryDocumentMinifier.minify(
            "query getWarrantiesList {\n"
                    + "  getAllWarranties {\n"
                    + "    __typename\n"
                    + "    id\n"
                    + "    title\n"
                    + "    brand\n"
                    + "    model\n"
                    + "    serial_number\n"
                    + "    starting_date\n"
                    + "    expiry_date\n"
                    + "    description\n"
                    + "    category_id\n"
                    + "  }\n"
                    + "}"
    );

    public static final OperationName OPERATION_NAME = new OperationName() {
        @Override
        public String name() {
            return "getWarrantiesList";
        }
    };

    private final Operation.Variables variables;

    public GetWarrantiesListQuery() {
        this.variables = Operation.EMPTY_VARIABLES;
    }

    @Override
    public String operationId() {
        return OPERATION_ID;
    }

    @Override
    public String queryDocument() {
        return QUERY_DOCUMENT;
    }

    @Override
    public GetWarrantiesListQuery.Data wrapData(GetWarrantiesListQuery.Data data) {
        return data;
    }

    @Override
    public Operation.Variables variables() {
        return variables;
    }

    @Override
    public ResponseFieldMapper<GetWarrantiesListQuery.Data> responseFieldMapper() {
        return new Data.Mapper();
    }

    public static Builder builder() {
        return new Builder();
    }

    @Override
    public OperationName name() {
        return OPERATION_NAME;
    }

    @Override
    @NotNull
    public Response<GetWarrantiesListQuery.Data> parse(@NotNull final BufferedSource source,
                                                       @NotNull final ScalarTypeAdapters scalarTypeAdapters) throws IOException {
        return SimpleOperationResponseParser.parse(source, this, scalarTypeAdapters);
    }

    @Override
    @NotNull
    public Response<GetWarrantiesListQuery.Data> parse(@NotNull final ByteString byteString,
                                                       @NotNull final ScalarTypeAdapters scalarTypeAdapters) throws IOException {
        return parse(new Buffer().write(byteString), scalarTypeAdapters);
    }

    @Override
    @NotNull
    public Response<GetWarrantiesListQuery.Data> parse(@NotNull final BufferedSource source) throws
            IOException {
        return parse(source, ScalarTypeAdapters.DEFAULT);
    }

    @Override
    @NotNull
    public Response<GetWarrantiesListQuery.Data> parse(@NotNull final ByteString byteString) throws
            IOException {
        return parse(byteString, ScalarTypeAdapters.DEFAULT);
    }

    @Override
    @NotNull
    public ByteString composeRequestBody(@NotNull final ScalarTypeAdapters scalarTypeAdapters) {
        return OperationRequestBodyComposer.compose(this, false, true, scalarTypeAdapters);
    }

    @NotNull
    @Override
    public ByteString composeRequestBody() {
        return OperationRequestBodyComposer.compose(this, false, true, ScalarTypeAdapters.DEFAULT);
    }

    @Override
    @NotNull
    public ByteString composeRequestBody(final boolean autoPersistQueries,
                                         final boolean withQueryDocument, @NotNull final ScalarTypeAdapters scalarTypeAdapters) {
        return OperationRequestBodyComposer.compose(this, autoPersistQueries, withQueryDocument, scalarTypeAdapters);
    }

    public static final class Builder {
        Builder() {
        }

        public GetWarrantiesListQuery build() {
            return new GetWarrantiesListQuery();
        }
    }

    /**
     * Data from the response after executing this GraphQL operation
     */
    public static class Data implements Operation.Data {
        static final ResponseField[] $responseFields = {
                ResponseField.forList("getAllWarranties", "getAllWarranties", null, false, Collections.<ResponseField.Condition>emptyList())
        };

        final @NotNull
        List<GetAllWarranty> getAllWarranties;

        private transient volatile String $toString;

        private transient volatile int $hashCode;

        private transient volatile boolean $hashCodeMemoized;

        public Data(@NotNull List<GetAllWarranty> getAllWarranties) {
            this.getAllWarranties = Utils.checkNotNull(getAllWarranties, "getAllWarranties == null");
        }

        public @NotNull
        List<GetAllWarranty> getAllWarranties() {
            return this.getAllWarranties;
        }

        @SuppressWarnings({"rawtypes", "unchecked"})
        public ResponseFieldMarshaller marshaller() {
            return new ResponseFieldMarshaller() {
                @Override
                public void marshal(ResponseWriter writer) {
                    writer.writeList($responseFields[0], getAllWarranties, new ResponseWriter.ListWriter() {
                        @Override
                        public void write(List items, ResponseWriter.ListItemWriter listItemWriter) {
                            for (Object item : items) {
                                listItemWriter.writeObject(((GetAllWarranty) item).marshaller());
                            }
                        }
                    });
                }
            };
        }

        @Override
        public String toString() {
            if ($toString == null) {
                $toString = "Data{"
                        + "getAllWarranties=" + getAllWarranties
                        + "}";
            }
            return $toString;
        }

        @Override
        public boolean equals(Object o) {
            if (o == this) {
                return true;
            }
            if (o instanceof Data) {
                Data that = (Data) o;
                return this.getAllWarranties.equals(that.getAllWarranties);
            }
            return false;
        }

        @Override
        public int hashCode() {
            if (!$hashCodeMemoized) {
                int h = 1;
                h *= 1000003;
                h ^= getAllWarranties.hashCode();
                $hashCode = h;
                $hashCodeMemoized = true;
            }
            return $hashCode;
        }

        public static final class Mapper implements ResponseFieldMapper<Data> {
            final GetAllWarranty.Mapper getAllWarrantyFieldMapper = new GetAllWarranty.Mapper();

            @Override
            public Data map(ResponseReader reader) {
                final List<GetAllWarranty> getAllWarranties = reader.readList($responseFields[0], new ResponseReader.ListReader<GetAllWarranty>() {
                    @Override
                    public GetAllWarranty read(ResponseReader.ListItemReader listItemReader) {
                        return listItemReader.readObject(new ResponseReader.ObjectReader<GetAllWarranty>() {
                            @Override
                            public GetAllWarranty read(ResponseReader reader) {
                                return getAllWarrantyFieldMapper.map(reader);
                            }
                        });
                    }
                });
                return new Data(getAllWarranties);
            }
        }
    }

    public static class GetAllWarranty {
        static final ResponseField[] $responseFields = {
                ResponseField.forString("__typename", "__typename", null, false, Collections.<ResponseField.Condition>emptyList()),
                ResponseField.forCustomType("id", "id", null, false, CustomType.ID, Collections.<ResponseField.Condition>emptyList()),
                ResponseField.forString("title", "title", null, false, Collections.<ResponseField.Condition>emptyList()),
                ResponseField.forString("brand", "brand", null, true, Collections.<ResponseField.Condition>emptyList()),
                ResponseField.forString("model", "model", null, true, Collections.<ResponseField.Condition>emptyList()),
                ResponseField.forString("serial_number", "serial_number", null, true, Collections.<ResponseField.Condition>emptyList()),
                ResponseField.forCustomType("starting_date", "starting_date", null, false, CustomType.DATE, Collections.<ResponseField.Condition>emptyList()),
                ResponseField.forCustomType("expiry_date", "expiry_date", null, false, CustomType.DATE, Collections.<ResponseField.Condition>emptyList()),
                ResponseField.forString("description", "description", null, true, Collections.<ResponseField.Condition>emptyList()),
                ResponseField.forCustomType("category_id", "category_id", null, true, CustomType.ID, Collections.<ResponseField.Condition>emptyList())
        };

        final @NotNull
        String __typename;

        final @NotNull
        String id;

        final @NotNull
        String title;

        final @Nullable
        String brand;

        final @Nullable
        String model;

        final @Nullable
        String serial_number;

        final @NotNull
        Object starting_date;

        final @NotNull
        Object expiry_date;

        final @Nullable
        String description;

        final @Nullable
        String category_id;

        private transient volatile String $toString;

        private transient volatile int $hashCode;

        private transient volatile boolean $hashCodeMemoized;

        public GetAllWarranty(@NotNull String __typename, @NotNull String id, @NotNull String title,
                              @Nullable String brand, @Nullable String model, @Nullable String serial_number,
                              @NotNull Object starting_date, @NotNull Object expiry_date, @Nullable String description,
                              @Nullable String category_id) {
            this.__typename = Utils.checkNotNull(__typename, "__typename == null");
            this.id = Utils.checkNotNull(id, "id == null");
            this.title = Utils.checkNotNull(title, "title == null");
            this.brand = brand;
            this.model = model;
            this.serial_number = serial_number;
            this.starting_date = Utils.checkNotNull(starting_date, "starting_date == null");
            this.expiry_date = Utils.checkNotNull(expiry_date, "expiry_date == null");
            this.description = description;
            this.category_id = category_id;
        }

        public @NotNull
        String __typename() {
            return this.__typename;
        }

        public @NotNull
        String id() {
            return this.id;
        }

        public @NotNull
        String title() {
            return this.title;
        }

        public @Nullable
        String brand() {
            return this.brand;
        }

        public @Nullable
        String model() {
            return this.model;
        }

        public @Nullable
        String serial_number() {
            return this.serial_number;
        }

        public @NotNull
        Object starting_date() {
            return this.starting_date;
        }

        public @NotNull
        Object expiry_date() {
            return this.expiry_date;
        }

        public @Nullable
        String description() {
            return this.description;
        }

        public @Nullable
        String category_id() {
            return this.category_id;
        }

        @SuppressWarnings({"rawtypes", "unchecked"})
        public ResponseFieldMarshaller marshaller() {
            return new ResponseFieldMarshaller() {
                @Override
                public void marshal(ResponseWriter writer) {
                    writer.writeString($responseFields[0], __typename);
                    writer.writeCustom((ResponseField.CustomTypeField) $responseFields[1], id);
                    writer.writeString($responseFields[2], title);
                    writer.writeString($responseFields[3], brand);
                    writer.writeString($responseFields[4], model);
                    writer.writeString($responseFields[5], serial_number);
                    writer.writeCustom((ResponseField.CustomTypeField) $responseFields[6], starting_date);
                    writer.writeCustom((ResponseField.CustomTypeField) $responseFields[7], expiry_date);
                    writer.writeString($responseFields[8], description);
                    writer.writeCustom((ResponseField.CustomTypeField) $responseFields[9], category_id);
                }
            };
        }

        @Override
        public String toString() {
            if ($toString == null) {
                $toString = "GetAllWarranty{"
                        + "__typename=" + __typename + ", "
                        + "id=" + id + ", "
                        + "title=" + title + ", "
                        + "brand=" + brand + ", "
                        + "model=" + model + ", "
                        + "serial_number=" + serial_number + ", "
                        + "starting_date=" + starting_date + ", "
                        + "expiry_date=" + expiry_date + ", "
                        + "description=" + description + ", "
                        + "category_id=" + category_id
                        + "}";
            }
            return $toString;
        }

        @Override
        public boolean equals(Object o) {
            if (o == this) {
                return true;
            }
            if (o instanceof GetAllWarranty) {
                GetAllWarranty that = (GetAllWarranty) o;
                return this.__typename.equals(that.__typename)
                        && this.id.equals(that.id)
                        && this.title.equals(that.title)
                        && ((this.brand == null) ? (that.brand == null) : this.brand.equals(that.brand))
                        && ((this.model == null) ? (that.model == null) : this.model.equals(that.model))
                        && ((this.serial_number == null) ? (that.serial_number == null) : this.serial_number.equals(that.serial_number))
                        && this.starting_date.equals(that.starting_date)
                        && this.expiry_date.equals(that.expiry_date)
                        && ((this.description == null) ? (that.description == null) : this.description.equals(that.description))
                        && ((this.category_id == null) ? (that.category_id == null) : this.category_id.equals(that.category_id));
            }
            return false;
        }

        @Override
        public int hashCode() {
            if (!$hashCodeMemoized) {
                int h = 1;
                h *= 1000003;
                h ^= __typename.hashCode();
                h *= 1000003;
                h ^= id.hashCode();
                h *= 1000003;
                h ^= title.hashCode();
                h *= 1000003;
                h ^= (brand == null) ? 0 : brand.hashCode();
                h *= 1000003;
                h ^= (model == null) ? 0 : model.hashCode();
                h *= 1000003;
                h ^= (serial_number == null) ? 0 : serial_number.hashCode();
                h *= 1000003;
                h ^= starting_date.hashCode();
                h *= 1000003;
                h ^= expiry_date.hashCode();
                h *= 1000003;
                h ^= (description == null) ? 0 : description.hashCode();
                h *= 1000003;
                h ^= (category_id == null) ? 0 : category_id.hashCode();
                $hashCode = h;
                $hashCodeMemoized = true;
            }
            return $hashCode;
        }

        public static final class Mapper implements ResponseFieldMapper<GetAllWarranty> {
            @Override
            public GetAllWarranty map(ResponseReader reader) {
                final String __typename = reader.readString($responseFields[0]);
                final String id = reader.readCustomType((ResponseField.CustomTypeField) $responseFields[1]);
                final String title = reader.readString($responseFields[2]);
                final String brand = reader.readString($responseFields[3]);
                final String model = reader.readString($responseFields[4]);
                final String serial_number = reader.readString($responseFields[5]);
                final Object starting_date = reader.readCustomType((ResponseField.CustomTypeField) $responseFields[6]);
                final Object expiry_date = reader.readCustomType((ResponseField.CustomTypeField) $responseFields[7]);
                final String description = reader.readString($responseFields[8]);
                final String category_id = reader.readCustomType((ResponseField.CustomTypeField) $responseFields[9]);
                return new GetAllWarranty(__typename, id, title, brand, model, serial_number, starting_date, expiry_date, description, category_id);
            }
        }
    }
}